const fee=10000;let db,admin=false,members=[],expenses=[];const names=['ADIBA','ADIT','ADIT TOTO','AFRI PB','AKVIL','ALDI','AMAR','ANAS','ARMA PB','AYU','BU DESY','DIKA ROCA','DIKA STIEBEL','DINA','DIVA','EGI','FARRA','FAUZAN','FEBRI','FIA','FITRI','FIQI','GITA','HAMDAN','HANAFI','HANNA','ILYAS','IRMA','ISKANDAR','KIA','MARINA','MAYA','MIA','MILA','MISBAH PB','MULYA','NADILA PB','NINA','NUR','PAK AGUNG','RAFI','REY','REZA','REZA PB','RIAN ELITE','RIAN WASSER','RINA','RISKY ACME','RIZKY ARISTON','SINDY','TETI','YESI'];const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);const mon=()=>$('month').value;
function toggleAdmin(){if(admin){admin=false;render();$('status').textContent='Mode lihat aktif.';$('adminBtn').textContent='Edit sebagai Admin';return}let p=prompt('Masukkan password admin:');if(p===ADMIN_PASSWORD){admin=true;$('status').textContent='Mode admin aktif.';$('adminBtn').textContent='Keluar dari mode admin';render()}else if(p!==null)alert('Password salah.')}
async function load(){if(!db){$('status').textContent='Isi config.js terlebih dahulu.';members=names.map(name=>({name}));render();return}let m=mon();let a=await db.from('members').select('*').order('name');members=a.data?.length?a.data:names.map(name=>({name}));let p=await db.from('payments').select('*').eq('month',m);let e=await db.from('expenses').select('*').eq('month',m).order('created_at');expenses=e.data||[];render(p.data||[])}
function render(payments=[]){let paid=new Set(payments.filter(x=>x.paid).map(x=>x.member_name));members.sort((a,b)=>a.name.localeCompare(b.name));$('members').innerHTML=members.map(x=>`<label class="member"><input class="paybox" data-name="${x.name}" type="checkbox" ${paid.has(x.name)?'checked':''} ${admin?'':'disabled'}>${x.name}<span class="paid">${paid.has(x.name)?'Lunas':''}</span></label>`).join('');document.querySelectorAll('.admin-only').forEach(x=>x.hidden=!admin);
$('expenses').innerHTML=expenses.map(x=>`<div class="row"><span>${x.name}<small>${x.note||''}</small></span><b>${money(x.amount)}</b> ${admin?`<button onclick="deleteExpense('${x.id}')" style="background:red; color:white; border:none; padding:2px 6px; border-radius:4px; cursor:pointer; margin-left:8px;">Hapus</button>`:''}</div>`).join('');
let income=paid.size*fee,out=expenses.reduce((s,x)=>s+Number(x.amount),0);$('income').textContent=money(income);$('expense').textContent=money(out);$('balance').textContent=money(income-out);$('opening').textContent=money(0)}
async function savePayments(){let rows=[...document.querySelectorAll('.paybox')].map(i=>({month:mon(),member_name:i.dataset.name,paid:i.checked,amount:i.checked?fee:0}));let d=await db.from('payments').delete().eq('month',mon());if(d.error)return alert(d.error.message);let x=await db.from('payments').insert(rows);if(x.error)alert(x.error.message);else load()}
async function addExpense(e){e.preventDefault();let x=await db.from('expenses').insert({month:mon(),name:$('expenseName').value,amount:Number($('expenseAmount').value),note:$('expenseNote').value});if(x.error)alert(x.error.message);else{e.target.reset();load()}}async function deleteExpense(id) {
    if (!confirm('Apakah Anda yakin ingin menghapus pengeluaran ini?')) return;
    let x = await db.from('expenses').delete().eq('id', id);
    if (x.error) {
        alert(x.error.message);
    } else {
        load(); // Memuat ulang data setelah berhasil dihapus
    }
}
$('month').value=new Date().toISOString().slice(0,7);if(SUPABASE_URL.startsWith('http'))db=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);$('month').addEventListener('change',load);load();